//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWebApplication.CalculationsWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculationsWS.CalculationsSoap")]
    public interface CalculationsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNumbers", ReplyAction="*")]
        int AddNumbers(int FirstNum, int SecondNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNumbers", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddNumbersAsync(int FirstNum, int SecondNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubtractNumbers", ReplyAction="*")]
        int SubtractNumbers(int FirstNum, int SecondNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubtractNumbers", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SubtractNumbersAsync(int FirstNum, int SecondNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MultiplyNumbers", ReplyAction="*")]
        int MultiplyNumbers(int FirstNum, int SecondNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MultiplyNumbers", ReplyAction="*")]
        System.Threading.Tasks.Task<int> MultiplyNumbersAsync(int FirstNum, int SecondNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DivideNumbers", ReplyAction="*")]
        int DivideNumbers(int FirstNum, int SecondNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DivideNumbers", ReplyAction="*")]
        System.Threading.Tasks.Task<int> DivideNumbersAsync(int FirstNum, int SecondNum);
        
        // CODEGEN: Generating message contract since element name GetAllPreviousCalculationsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPreviousCalculations", ReplyAction="*")]
        CalculatorWebApplication.CalculationsWS.GetAllPreviousCalculationsResponse GetAllPreviousCalculations(CalculatorWebApplication.CalculationsWS.GetAllPreviousCalculationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPreviousCalculations", ReplyAction="*")]
        System.Threading.Tasks.Task<CalculatorWebApplication.CalculationsWS.GetAllPreviousCalculationsResponse> GetAllPreviousCalculationsAsync(CalculatorWebApplication.CalculationsWS.GetAllPreviousCalculationsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPreviousCalculationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPreviousCalculations", Namespace="http://tempuri.org/", Order=0)]
        public CalculatorWebApplication.CalculationsWS.GetAllPreviousCalculationsRequestBody Body;
        
        public GetAllPreviousCalculationsRequest() {
        }
        
        public GetAllPreviousCalculationsRequest(CalculatorWebApplication.CalculationsWS.GetAllPreviousCalculationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllPreviousCalculationsRequestBody {
        
        public GetAllPreviousCalculationsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPreviousCalculationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPreviousCalculationsResponse", Namespace="http://tempuri.org/", Order=0)]
        public CalculatorWebApplication.CalculationsWS.GetAllPreviousCalculationsResponseBody Body;
        
        public GetAllPreviousCalculationsResponse() {
        }
        
        public GetAllPreviousCalculationsResponse(CalculatorWebApplication.CalculationsWS.GetAllPreviousCalculationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllPreviousCalculationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CalculatorWebApplication.CalculationsWS.ArrayOfString GetAllPreviousCalculationsResult;
        
        public GetAllPreviousCalculationsResponseBody() {
        }
        
        public GetAllPreviousCalculationsResponseBody(CalculatorWebApplication.CalculationsWS.ArrayOfString GetAllPreviousCalculationsResult) {
            this.GetAllPreviousCalculationsResult = GetAllPreviousCalculationsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculationsSoapChannel : CalculatorWebApplication.CalculationsWS.CalculationsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculationsSoapClient : System.ServiceModel.ClientBase<CalculatorWebApplication.CalculationsWS.CalculationsSoap>, CalculatorWebApplication.CalculationsWS.CalculationsSoap {
        
        public CalculationsSoapClient() {
        }
        
        public CalculationsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculationsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculationsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculationsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddNumbers(int FirstNum, int SecondNum) {
            return base.Channel.AddNumbers(FirstNum, SecondNum);
        }
        
        public System.Threading.Tasks.Task<int> AddNumbersAsync(int FirstNum, int SecondNum) {
            return base.Channel.AddNumbersAsync(FirstNum, SecondNum);
        }
        
        public int SubtractNumbers(int FirstNum, int SecondNum) {
            return base.Channel.SubtractNumbers(FirstNum, SecondNum);
        }
        
        public System.Threading.Tasks.Task<int> SubtractNumbersAsync(int FirstNum, int SecondNum) {
            return base.Channel.SubtractNumbersAsync(FirstNum, SecondNum);
        }
        
        public int MultiplyNumbers(int FirstNum, int SecondNum) {
            return base.Channel.MultiplyNumbers(FirstNum, SecondNum);
        }
        
        public System.Threading.Tasks.Task<int> MultiplyNumbersAsync(int FirstNum, int SecondNum) {
            return base.Channel.MultiplyNumbersAsync(FirstNum, SecondNum);
        }
        
        public int DivideNumbers(int FirstNum, int SecondNum) {
            return base.Channel.DivideNumbers(FirstNum, SecondNum);
        }
        
        public System.Threading.Tasks.Task<int> DivideNumbersAsync(int FirstNum, int SecondNum) {
            return base.Channel.DivideNumbersAsync(FirstNum, SecondNum);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculatorWebApplication.CalculationsWS.GetAllPreviousCalculationsResponse CalculatorWebApplication.CalculationsWS.CalculationsSoap.GetAllPreviousCalculations(CalculatorWebApplication.CalculationsWS.GetAllPreviousCalculationsRequest request) {
            return base.Channel.GetAllPreviousCalculations(request);
        }
        
        public CalculatorWebApplication.CalculationsWS.ArrayOfString GetAllPreviousCalculations() {
            CalculatorWebApplication.CalculationsWS.GetAllPreviousCalculationsRequest inValue = new CalculatorWebApplication.CalculationsWS.GetAllPreviousCalculationsRequest();
            inValue.Body = new CalculatorWebApplication.CalculationsWS.GetAllPreviousCalculationsRequestBody();
            CalculatorWebApplication.CalculationsWS.GetAllPreviousCalculationsResponse retVal = ((CalculatorWebApplication.CalculationsWS.CalculationsSoap)(this)).GetAllPreviousCalculations(inValue);
            return retVal.Body.GetAllPreviousCalculationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculatorWebApplication.CalculationsWS.GetAllPreviousCalculationsResponse> CalculatorWebApplication.CalculationsWS.CalculationsSoap.GetAllPreviousCalculationsAsync(CalculatorWebApplication.CalculationsWS.GetAllPreviousCalculationsRequest request) {
            return base.Channel.GetAllPreviousCalculationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculatorWebApplication.CalculationsWS.GetAllPreviousCalculationsResponse> GetAllPreviousCalculationsAsync() {
            CalculatorWebApplication.CalculationsWS.GetAllPreviousCalculationsRequest inValue = new CalculatorWebApplication.CalculationsWS.GetAllPreviousCalculationsRequest();
            inValue.Body = new CalculatorWebApplication.CalculationsWS.GetAllPreviousCalculationsRequestBody();
            return ((CalculatorWebApplication.CalculationsWS.CalculationsSoap)(this)).GetAllPreviousCalculationsAsync(inValue);
        }
    }
}
