//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWebService.Tests.CalculationsWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculationsWS.CalculationsSoap")]
    public interface CalculationsSoap {
        
        // CODEGEN: Generating message contract since element name valueToAdd from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddToListOfCalculations", ReplyAction="*")]
        CalculatorWebService.Tests.CalculationsWS.AddToListOfCalculationsResponse AddToListOfCalculations(CalculatorWebService.Tests.CalculationsWS.AddToListOfCalculationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddToListOfCalculations", ReplyAction="*")]
        System.Threading.Tasks.Task<CalculatorWebService.Tests.CalculationsWS.AddToListOfCalculationsResponse> AddToListOfCalculationsAsync(CalculatorWebService.Tests.CalculationsWS.AddToListOfCalculationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNumbers", ReplyAction="*")]
        int AddNumbers(int FirstNum, int SecondNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNumbers", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddNumbersAsync(int FirstNum, int SecondNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubtractNumbers", ReplyAction="*")]
        int SubtractNumbers(int FirstNum, int SecondNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubtractNumbers", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SubtractNumbersAsync(int FirstNum, int SecondNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MultiplyNumbers", ReplyAction="*")]
        int MultiplyNumbers(int FirstNum, int SecondNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MultiplyNumbers", ReplyAction="*")]
        System.Threading.Tasks.Task<int> MultiplyNumbersAsync(int FirstNum, int SecondNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DivideNumbers", ReplyAction="*")]
        int DivideNumbers(int FirstNum, int SecondNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DivideNumbers", ReplyAction="*")]
        System.Threading.Tasks.Task<int> DivideNumbersAsync(int FirstNum, int SecondNum);
        
        // CODEGEN: Generating message contract since element name GetAllPreviousCalculationsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPreviousCalculations", ReplyAction="*")]
        CalculatorWebService.Tests.CalculationsWS.GetAllPreviousCalculationsResponse GetAllPreviousCalculations(CalculatorWebService.Tests.CalculationsWS.GetAllPreviousCalculationsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPreviousCalculations", ReplyAction="*")]
        System.Threading.Tasks.Task<CalculatorWebService.Tests.CalculationsWS.GetAllPreviousCalculationsResponse> GetAllPreviousCalculationsAsync(CalculatorWebService.Tests.CalculationsWS.GetAllPreviousCalculationsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddToListOfCalculationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddToListOfCalculations", Namespace="http://tempuri.org/", Order=0)]
        public CalculatorWebService.Tests.CalculationsWS.AddToListOfCalculationsRequestBody Body;
        
        public AddToListOfCalculationsRequest() {
        }
        
        public AddToListOfCalculationsRequest(CalculatorWebService.Tests.CalculationsWS.AddToListOfCalculationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddToListOfCalculationsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string valueToAdd;
        
        public AddToListOfCalculationsRequestBody() {
        }
        
        public AddToListOfCalculationsRequestBody(string valueToAdd) {
            this.valueToAdd = valueToAdd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddToListOfCalculationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddToListOfCalculationsResponse", Namespace="http://tempuri.org/", Order=0)]
        public CalculatorWebService.Tests.CalculationsWS.AddToListOfCalculationsResponseBody Body;
        
        public AddToListOfCalculationsResponse() {
        }
        
        public AddToListOfCalculationsResponse(CalculatorWebService.Tests.CalculationsWS.AddToListOfCalculationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddToListOfCalculationsResponseBody {
        
        public AddToListOfCalculationsResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPreviousCalculationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPreviousCalculations", Namespace="http://tempuri.org/", Order=0)]
        public CalculatorWebService.Tests.CalculationsWS.GetAllPreviousCalculationsRequestBody Body;
        
        public GetAllPreviousCalculationsRequest() {
        }
        
        public GetAllPreviousCalculationsRequest(CalculatorWebService.Tests.CalculationsWS.GetAllPreviousCalculationsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllPreviousCalculationsRequestBody {
        
        public GetAllPreviousCalculationsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPreviousCalculationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPreviousCalculationsResponse", Namespace="http://tempuri.org/", Order=0)]
        public CalculatorWebService.Tests.CalculationsWS.GetAllPreviousCalculationsResponseBody Body;
        
        public GetAllPreviousCalculationsResponse() {
        }
        
        public GetAllPreviousCalculationsResponse(CalculatorWebService.Tests.CalculationsWS.GetAllPreviousCalculationsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllPreviousCalculationsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CalculatorWebService.Tests.CalculationsWS.ArrayOfString GetAllPreviousCalculationsResult;
        
        public GetAllPreviousCalculationsResponseBody() {
        }
        
        public GetAllPreviousCalculationsResponseBody(CalculatorWebService.Tests.CalculationsWS.ArrayOfString GetAllPreviousCalculationsResult) {
            this.GetAllPreviousCalculationsResult = GetAllPreviousCalculationsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculationsSoapChannel : CalculatorWebService.Tests.CalculationsWS.CalculationsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculationsSoapClient : System.ServiceModel.ClientBase<CalculatorWebService.Tests.CalculationsWS.CalculationsSoap>, CalculatorWebService.Tests.CalculationsWS.CalculationsSoap {
        
        public CalculationsSoapClient() {
        }
        
        public CalculationsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculationsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculationsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculationsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculatorWebService.Tests.CalculationsWS.AddToListOfCalculationsResponse CalculatorWebService.Tests.CalculationsWS.CalculationsSoap.AddToListOfCalculations(CalculatorWebService.Tests.CalculationsWS.AddToListOfCalculationsRequest request) {
            return base.Channel.AddToListOfCalculations(request);
        }
        
        public void AddToListOfCalculations(string valueToAdd) {
            CalculatorWebService.Tests.CalculationsWS.AddToListOfCalculationsRequest inValue = new CalculatorWebService.Tests.CalculationsWS.AddToListOfCalculationsRequest();
            inValue.Body = new CalculatorWebService.Tests.CalculationsWS.AddToListOfCalculationsRequestBody();
            inValue.Body.valueToAdd = valueToAdd;
            CalculatorWebService.Tests.CalculationsWS.AddToListOfCalculationsResponse retVal = ((CalculatorWebService.Tests.CalculationsWS.CalculationsSoap)(this)).AddToListOfCalculations(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculatorWebService.Tests.CalculationsWS.AddToListOfCalculationsResponse> CalculatorWebService.Tests.CalculationsWS.CalculationsSoap.AddToListOfCalculationsAsync(CalculatorWebService.Tests.CalculationsWS.AddToListOfCalculationsRequest request) {
            return base.Channel.AddToListOfCalculationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculatorWebService.Tests.CalculationsWS.AddToListOfCalculationsResponse> AddToListOfCalculationsAsync(string valueToAdd) {
            CalculatorWebService.Tests.CalculationsWS.AddToListOfCalculationsRequest inValue = new CalculatorWebService.Tests.CalculationsWS.AddToListOfCalculationsRequest();
            inValue.Body = new CalculatorWebService.Tests.CalculationsWS.AddToListOfCalculationsRequestBody();
            inValue.Body.valueToAdd = valueToAdd;
            return ((CalculatorWebService.Tests.CalculationsWS.CalculationsSoap)(this)).AddToListOfCalculationsAsync(inValue);
        }
        
        public int AddNumbers(int FirstNum, int SecondNum) {
            return base.Channel.AddNumbers(FirstNum, SecondNum);
        }
        
        public System.Threading.Tasks.Task<int> AddNumbersAsync(int FirstNum, int SecondNum) {
            return base.Channel.AddNumbersAsync(FirstNum, SecondNum);
        }
        
        public int SubtractNumbers(int FirstNum, int SecondNum) {
            return base.Channel.SubtractNumbers(FirstNum, SecondNum);
        }
        
        public System.Threading.Tasks.Task<int> SubtractNumbersAsync(int FirstNum, int SecondNum) {
            return base.Channel.SubtractNumbersAsync(FirstNum, SecondNum);
        }
        
        public int MultiplyNumbers(int FirstNum, int SecondNum) {
            return base.Channel.MultiplyNumbers(FirstNum, SecondNum);
        }
        
        public System.Threading.Tasks.Task<int> MultiplyNumbersAsync(int FirstNum, int SecondNum) {
            return base.Channel.MultiplyNumbersAsync(FirstNum, SecondNum);
        }
        
        public int DivideNumbers(int FirstNum, int SecondNum) {
            return base.Channel.DivideNumbers(FirstNum, SecondNum);
        }
        
        public System.Threading.Tasks.Task<int> DivideNumbersAsync(int FirstNum, int SecondNum) {
            return base.Channel.DivideNumbersAsync(FirstNum, SecondNum);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CalculatorWebService.Tests.CalculationsWS.GetAllPreviousCalculationsResponse CalculatorWebService.Tests.CalculationsWS.CalculationsSoap.GetAllPreviousCalculations(CalculatorWebService.Tests.CalculationsWS.GetAllPreviousCalculationsRequest request) {
            return base.Channel.GetAllPreviousCalculations(request);
        }
        
        public CalculatorWebService.Tests.CalculationsWS.ArrayOfString GetAllPreviousCalculations() {
            CalculatorWebService.Tests.CalculationsWS.GetAllPreviousCalculationsRequest inValue = new CalculatorWebService.Tests.CalculationsWS.GetAllPreviousCalculationsRequest();
            inValue.Body = new CalculatorWebService.Tests.CalculationsWS.GetAllPreviousCalculationsRequestBody();
            CalculatorWebService.Tests.CalculationsWS.GetAllPreviousCalculationsResponse retVal = ((CalculatorWebService.Tests.CalculationsWS.CalculationsSoap)(this)).GetAllPreviousCalculations(inValue);
            return retVal.Body.GetAllPreviousCalculationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CalculatorWebService.Tests.CalculationsWS.GetAllPreviousCalculationsResponse> CalculatorWebService.Tests.CalculationsWS.CalculationsSoap.GetAllPreviousCalculationsAsync(CalculatorWebService.Tests.CalculationsWS.GetAllPreviousCalculationsRequest request) {
            return base.Channel.GetAllPreviousCalculationsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CalculatorWebService.Tests.CalculationsWS.GetAllPreviousCalculationsResponse> GetAllPreviousCalculationsAsync() {
            CalculatorWebService.Tests.CalculationsWS.GetAllPreviousCalculationsRequest inValue = new CalculatorWebService.Tests.CalculationsWS.GetAllPreviousCalculationsRequest();
            inValue.Body = new CalculatorWebService.Tests.CalculationsWS.GetAllPreviousCalculationsRequestBody();
            return ((CalculatorWebService.Tests.CalculationsWS.CalculationsSoap)(this)).GetAllPreviousCalculationsAsync(inValue);
        }
    }
}
